import type { ContentImage, Profile } from '@/content/types';
import type { Locale } from '@/i18n/routing';
import { OWNER_INPUT_PLACEHOLDER } from '@/i18n/messages';
// Generated by `pnpm seo:share-images` (scripts/generate-share-images.mjs): 1200 × 630, the
// confirmed identity + the approved portrait (unmodified source, Phase 3 crop). Build-hashed,
// served from /_next/static/media with immutable caching; no CMS or private file involved.
import shareEn from '@/assets/share/share-en.png';
import shareAr from '@/assets/share/share-ar.png';

const FILES = { en: shareEn, ar: shareAr } as const;

/** The built-in brand share image of a locale; alt = the identity shown on it. */
export function defaultShareImage(
  locale: Locale,
  profile: Pick<Profile, 'name' | 'title'> | null,
): ContentImage {
  const file = FILES[locale];
  const name = profile?.name ?? OWNER_INPUT_PLACEHOLDER;
  return {
    url: file.src,
    width: file.width,
    height: file.height,
    alt: profile ? `${name} — ${profile.title}` : name,
  };
}
