/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    projects: Project;
    experience: Experience;
    education: Education;
    certificates: Certificate;
    skills: Skill;
    media: Media;
    documents: Document;
    redirects: Redirect;
    users: User;
    'audit-log': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    experience: {
      projects: 'projects';
    };
    skills: {
      evidence: 'projects';
    };
    media: {
      usedAsCover: 'projects';
      usedInGalleries: 'projects';
    };
  };
  collectionsSelect: {
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    experience: ExperienceSelect<false> | ExperienceSelect<true>;
    education: EducationSelect<false> | EducationSelect<true>;
    certificates: CertificatesSelect<false> | CertificatesSelect<true>;
    skills: SkillsSelect<false> | SkillsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ar') | ('en' | 'ar')[];
  globals: {
    profile: Profile;
    'site-settings': SiteSetting;
    cv: Cv;
  };
  globalsSelect: {
    profile: ProfileSelect<false> | ProfileSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    cv: CvSelect<false> | CvSelect<true>;
  };
  locale: 'en' | 'ar';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Case studies shown on /projects and /projects/<slug>. Each language is public only when its Translation status is Approved.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * Page heading (H1) and list title.
   */
  title: string;
  /**
   * Lowercase, hyphen-separated (e.g. vision-system). Changing a published slug keeps the old URL working (permanent redirect).
   */
  slug: string;
  /**
   * One or two sentences under the title and in project lists (max 300 characters).
   */
  summary: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  problem?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  solution?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  architecture?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Verified outcomes only — no estimated or unverifiable metrics.
   */
  results?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Your role in this project.
   */
  role?: string | null;
  /**
   * Used for the Projects filter and to suggest related projects.
   */
  category?:
    | (
        | 'artificial-intelligence'
        | 'machine-learning'
        | 'computer-vision'
        | 'robotics'
        | 'software-engineering'
        | 'web'
        | 'mobile'
        | 'data'
        | 'other'
      )
    | null;
  /**
   * Month precision. Leave End empty for ongoing work.
   */
  timeline?: {
    start?: string | null;
    end?: string | null;
  };
  /**
   * Pick from Skills (or create one here). Each technology links to the Skills page and marks this project as evidence.
   */
  technologies?: (number | Skill)[] | null;
  /**
   * Optional: the role/organization this project was done in.
   */
  experience?: (number | null) | Experience;
  /**
   * External links (repository, demo, article). Opened in the same tab with rel safety.
   */
  links?:
    | {
        /**
         * Link text, per language.
         */
        label: string;
        url: string;
        kind?: ('repository' | 'demo' | 'article' | 'other') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown at the top of the page and in lists.
   */
  cover?: (number | null) | Media;
  /**
   * Additional images, shown in order in the Media section.
   */
  gallery?: (number | Media)[] | null;
  /**
   * Optional link to a video (http/https).
   */
  videoUrl?: string | null;
  /**
   * Unique, human-written. Required before publishing in each locale.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  /**
   * Show in “Selected work” on the homepage (first 6, by sort order).
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  /**
   * Per language. Public pages only show a language when it is Approved.
   */
  translationStatus?: ('draft' | 'in_review' | 'approved') | null;
  /**
   * Archived items disappear from the public site but keep their history.
   */
  archived?: boolean | null;
  archivedAt?: string | null;
  /**
   * Where this fact comes from (owner confirmation, certificate file…). Never public.
   */
  sourceNote?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Grouped by category on /skills. Projects that use a skill appear as its evidence automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills".
 */
export interface Skill {
  id: number;
  /**
   * Technology name — not translated (IL). No proficiency percentages (CONTENT_MODEL).
   */
  name: string;
  /**
   * Optional localized display label.
   */
  label?: string | null;
  category:
    | 'ai-ml'
    | 'programming'
    | 'backend'
    | 'frontend'
    | 'mobile'
    | 'devops-infrastructure'
    | 'databases'
    | 'tools'
    | 'other';
  /**
   * Only if the owner explicitly provides one. Never a number/percentage.
   */
  proficiencyLabel?: string | null;
  /**
   * Lower numbers appear first.
   */
  displayOrder?: number | null;
  evidence?: {
    docs?: (number | Project)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Per language. Public pages only show a language when it is Approved.
   */
  translationStatus?: ('draft' | 'in_review' | 'approved') | null;
  /**
   * Archived items disappear from the public site but keep their history.
   */
  archived?: boolean | null;
  archivedAt?: string | null;
  /**
   * Where this fact comes from (owner confirmation, certificate file…). Never public.
   */
  sourceNote?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Roles shown on /experience (newest first), the CV page and the homepage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience".
 */
export interface Experience {
  id: number;
  /**
   * Proper name — not translated.
   */
  organization: string;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Leave empty when the start date is not known — no period is then shown (never guess).
   */
  startDate?: string | null;
  /**
   * Leave empty for a current role (“Present”).
   */
  endDate?: string | null;
  technologies?: (number | Skill)[] | null;
  /**
   * External links (repository, demo, article). Opened in the same tab with rel safety.
   */
  links?:
    | {
        /**
         * Link text, per language.
         */
        label: string;
        url: string;
        kind?: ('repository' | 'demo' | 'article' | 'other') | null;
        id?: string | null;
      }[]
    | null;
  projects?: {
    docs?: (number | Project)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Per language. Public pages only show a language when it is Approved.
   */
  translationStatus?: ('draft' | 'in_review' | 'approved') | null;
  /**
   * Archived items disappear from the public site but keep their history.
   */
  archived?: boolean | null;
  archivedAt?: string | null;
  /**
   * Where this fact comes from (owner confirmation, certificate file…). Never public.
   */
  sourceNote?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * JPEG, PNG, WebP or AVIF (max 15 MB, max 12,000 px per side). Alt text is required in each language unless the image is decorative — without it, the image is not shown in that language. Public pages use optimized copies only; the original stays private. Delete = archive first, and only when unused.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Purely decorative images get empty alt text (SEO_MASTER §26).
   */
  decorative?: boolean | null;
  /**
   * Describe the image’s content/function. Required in each published language unless decorative.
   */
  alt?: string | null;
  caption?: string | null;
  originalFilename?: string | null;
  /**
   * Derivatives are generated during the upload itself (the upload fails if they cannot be made). Failed = a derivative is missing — re-upload the file.
   */
  optimizationStatus?: ('ready' | 'failed' | 'not-applicable') | null;
  optimizationDetail?: string | null;
  usedAsCover?: {
    docs?: (number | Project)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  usedInGalleries?: {
    docs?: (number | Project)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Archived items disappear from the public site but keep their history.
   */
  archived?: boolean | null;
  archivedAt?: string | null;
  /**
   * Where this fact comes from (owner confirmation, certificate file…). Never public.
   */
  sourceNote?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    full?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Shown on the About and CV pages (no page of its own).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "education".
 */
export interface Education {
  id: number;
  institution: string;
  degree: string;
  field?: string | null;
  startDate?: string | null;
  endDate?: string | null;
  /**
   * Choose “Year only” when only the years are known — the month is then never shown.
   */
  datePrecision?: ('month' | 'year') | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional, e.g. a diploma. Linked from the About page.
   */
  document?: (number | null) | Document;
  /**
   * Per language. Public pages only show a language when it is Approved.
   */
  translationStatus?: ('draft' | 'in_review' | 'approved') | null;
  /**
   * Archived items disappear from the public site but keep their history.
   */
  archived?: boolean | null;
  archivedAt?: string | null;
  /**
   * Where this fact comes from (owner confirmation, certificate file…). Never public.
   */
  sourceNote?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * PDF only (max 20 MB, no scripts, attachments or form submission). CV files, certificate files, diplomas. Served inline with noindex; each upload gets a new URL. Delete = archive first, and only when unused.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title?: string | null;
  originalFilename?: string | null;
  /**
   * Archived items disappear from the public site but keep their history.
   */
  archived?: boolean | null;
  archivedAt?: string | null;
  /**
   * Where this fact comes from (owner confirmation, certificate file…). Never public.
   */
  sourceNote?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Shown on /certificates (newest first) and the homepage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates".
 */
export interface Certificate {
  id: number;
  /**
   * Exact title as printed on the certificate (IL: do not translate blindly).
   */
  name: string;
  issuer: string;
  issueDate?: string | null;
  credentialId?: string | null;
  /**
   * The issuer’s own verification page, if one exists.
   */
  verificationUrl?: string | null;
  description?: string | null;
  /**
   * Certificate image or PDF, if available. Certificates may be published without a file (owner decision, 2026-09-28).
   */
  attachment?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null);
  /**
   * Per language. Public pages only show a language when it is Approved.
   */
  translationStatus?: ('draft' | 'in_review' | 'approved') | null;
  /**
   * Archived items disappear from the public site but keep their history.
   */
  archived?: boolean | null;
  archivedAt?: string | null;
  /**
   * Where this fact comes from (owner confirmation, certificate file…). Never public.
   */
  sourceNote?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Created automatically when a published project slug changes. Edit only if needed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to: string;
  statusCode?: ('308' | '307') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Accounts that can sign in to this CMS. There is no public sign-up.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Read-only history of every content change (who, what, when). Cannot be edited or deleted.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  collection: string;
  documentId: string;
  action: string;
  userEmail: string;
  locale?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'experience';
        value: number | Experience;
      } | null)
    | ({
        relationTo: 'education';
        value: number | Education;
      } | null)
    | ({
        relationTo: 'certificates';
        value: number | Certificate;
      } | null)
    | ({
        relationTo: 'skills';
        value: number | Skill;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  description?: T;
  problem?: T;
  solution?: T;
  architecture?: T;
  results?: T;
  role?: T;
  category?: T;
  timeline?:
    | T
    | {
        start?: T;
        end?: T;
      };
  technologies?: T;
  experience?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        kind?: T;
        id?: T;
      };
  cover?: T;
  gallery?: T;
  videoUrl?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  featured?: T;
  sortOrder?: T;
  translationStatus?: T;
  archived?: T;
  archivedAt?: T;
  sourceNote?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience_select".
 */
export interface ExperienceSelect<T extends boolean = true> {
  organization?: T;
  title?: T;
  description?: T;
  startDate?: T;
  endDate?: T;
  technologies?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        kind?: T;
        id?: T;
      };
  projects?: T;
  translationStatus?: T;
  archived?: T;
  archivedAt?: T;
  sourceNote?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "education_select".
 */
export interface EducationSelect<T extends boolean = true> {
  institution?: T;
  degree?: T;
  field?: T;
  startDate?: T;
  endDate?: T;
  datePrecision?: T;
  description?: T;
  document?: T;
  translationStatus?: T;
  archived?: T;
  archivedAt?: T;
  sourceNote?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates_select".
 */
export interface CertificatesSelect<T extends boolean = true> {
  name?: T;
  issuer?: T;
  issueDate?: T;
  credentialId?: T;
  verificationUrl?: T;
  description?: T;
  attachment?: T;
  translationStatus?: T;
  archived?: T;
  archivedAt?: T;
  sourceNote?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills_select".
 */
export interface SkillsSelect<T extends boolean = true> {
  name?: T;
  label?: T;
  category?: T;
  proficiencyLabel?: T;
  displayOrder?: T;
  evidence?: T;
  translationStatus?: T;
  archived?: T;
  archivedAt?: T;
  sourceNote?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  decorative?: T;
  alt?: T;
  caption?: T;
  originalFilename?: T;
  optimizationStatus?: T;
  optimizationDetail?: T;
  usedAsCover?: T;
  usedInGalleries?: T;
  archived?: T;
  archivedAt?: T;
  sourceNote?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        full?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  originalFilename?: T;
  archived?: T;
  archivedAt?: T;
  sourceNote?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  statusCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  collection?: T;
  documentId?: T;
  action?: T;
  userEmail?: T;
  locale?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Your identity (homepage H1, metadata), biography (About page), portrait, social profiles and public email (Contact page).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile".
 */
export interface Profile {
  id: number;
  name: string;
  /**
   * Professional title (owner-approved per language).
   */
  title: string;
  /**
   * Homepage introduction and the lead on the About page (max 400 characters).
   */
  shortBio?: string | null;
  /**
   * The About page exists only when this has text in that language.
   */
  longBio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional. When empty, the About page uses the approved portrait.jpg.
   */
  portrait?: (number | null) | Media;
  /**
   * Owner-confirmed profiles only (used for JSON-LD sameAs).
   */
  socialLinks?:
    | {
        network: 'github' | 'linkedin' | 'instagram' | 'other';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Public contact email — only if the owner chooses one.
   */
  email?: string | null;
  /**
   * Per language. Public pages only show a language when it is Approved.
   */
  translationStatus?: ('draft' | 'in_review' | 'approved') | null;
  /**
   * Where this fact comes from (owner confirmation, certificate file…). Never public.
   */
  sourceNote?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Site-wide search and share defaults. Leave a field empty to keep the built-in default. Page titles and descriptions of projects are edited on each project.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Home page in search results and share previews. Used in a language only when its Translation status is Approved.
   */
  seo?: {
    /**
     * Empty = “<name> — <title>” from Profile & contact.
     */
    title?: string | null;
    /**
     * Empty = “Official website of <name>, <title>.” (also the site description in structured data).
     */
    description?: string | null;
  };
  /**
   * Shown when a page without its own image is shared (projects use their cover). Landscape, ideally 1200 × 630 or larger, with alt text in each language. Empty = the built-in brand image.
   */
  shareImage?: (number | null) | Media;
  /**
   * Per language. Public pages only show a language when it is Approved.
   */
  translationStatus?: ('draft' | 'in_review' | 'approved') | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * One PDF per language. The /cv page and footer link exist only when “Download visible” is on.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cv".
 */
export interface Cv {
  id: number;
  /**
   * CV PDF for this language.
   */
  file?: (number | null) | Document;
  /**
   * Button text (default: “Download CV”).
   */
  label?: string | null;
  /**
   * e.g. 2026-09. Shown next to the download.
   */
  version?: string | null;
  /**
   * Per language. Turn on to publish the CV page and download link.
   */
  downloadVisible?: boolean | null;
  /**
   * Per language. Publishes the /cv page built from the site’s own content (experience, education, skills, certificates, contact) — with or without a PDF.
   */
  webCv?: boolean | null;
  /**
   * Per language. Public pages only show a language when it is Approved.
   */
  translationStatus?: ('draft' | 'in_review' | 'approved') | null;
  /**
   * Where this fact comes from (owner confirmation, certificate file…). Never public.
   */
  sourceNote?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile_select".
 */
export interface ProfileSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  shortBio?: T;
  longBio?: T;
  portrait?: T;
  socialLinks?:
    | T
    | {
        network?: T;
        url?: T;
        id?: T;
      };
  email?: T;
  translationStatus?: T;
  sourceNote?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  shareImage?: T;
  translationStatus?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cv_select".
 */
export interface CvSelect<T extends boolean = true> {
  file?: T;
  label?: T;
  version?: T;
  downloadVisible?: T;
  webCv?: T;
  translationStatus?: T;
  sourceNote?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}